name: SOLIDES Grid Test
favicon: null
layout_spectrum: 0.88806
typography_spectrum: 0.27073
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#ee2d10'
    - '#4af99b'
    - '#1c6346'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
